# Generated by Django 5.2.6 on 2025-09-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_completed_at_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
