# Generated by Django 5.2.6 on 2025-09-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_reminder_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_time',
        ),
    ]
