# Generated by Django 5.2.6 on 2025-09-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tag_subtask_tags_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
