# Generated by Django 5.2.6 on 2025-10-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_subtask_tags_remove_task_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
